urms_app_homepage:
    path:     /
    defaults: { _controller: URMSAppBundle:Page:index }

security_login:
    path:     /login
    defaults: { _controller: URMSAppBundle:Security:login }


security_logout:
    path:     /logout

login_check:
    path:     /login_check
    defaults: {_controller: URMSAppBundle:Security:loginCheck }

help_me:
    path:    /help_me
    defaults: {_controller: URMSAppBundle:Security:helpMe}

admin_addUser:
    path: /admin/add_user
    defaults: {_controller: URMSAppBundle:Admin:addUser}

admin_addDriver:
    path: /admin/add_driver
    defaults: {_controller: URMSAppBundle:Admin:addDriverAccount}

admin_addHall:
    path: /admin/add_hall
    defaults: {_controller: URMSAppBundle:Admin:addHall}

admin_addVehicle:
    path: /admin/add_vehicle
    defaults: {_controller: URMSAppBundle:Admin:addVehicle}

user_showDriverList:
    path: /show_driver
    defaults: {_controller: URMSAppBundle:Page:showDriverAccount}
user_showHall:
    path: /hall_type
    defaults: {_controller: URMSAppBundle:Page:hallType}
ùser_showVehicleList:
    path: /show_vehicle
    defaults: {_controller: URMSAppBundle:Page:getVehicleList}