services:
    user_provider:
        class: URMS\AppBundle\Security\User\UserProvider
#    urms_app.example:
#        class: URMS\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
