# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: URMSAppBundle:Login
    encoders:
        URMS\AppBundle\Entity\User:
            algorithm: bcrypt
        URMS\AppBundle\Entity\Login:
            algorithm: bcrypt
    role_hierarchy:
            ROLE_STUDENT:       ROLE_USER
            ROLE_STUFF:       ROLE_STUDENT
            ROLE_ADMIN: [ROLE_STUDENT, ROLE_STUFF]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: our_db_provider
            anonymous: true
            form_login:
                  login_path: /login
                  check_path: /login_check
                  csrf_parameter: _csrf_token
                  always_use_default_target_path: true
                  default_target_path: /
                  target_path_parameter: _target_path
            logout:
                  path: /logout
                  target: /login
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }